/* This file was generated by asn1gen */

package moo.codec.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

import moo.model.ASNEXAMPLES.*;
import static moo.codec.ASNEXAMPLES.ShadowBerToAsn.*;

@SuppressWarnings("unused")
public class BerToAsn {
  public static BookCover decode(
      final BookCover value,
      final ByteArrayWindow window) throws AsnException {
    final DetailedTlvFrame detailedFrame = TLV.readTlv(window);
    final TlvFrame frame = detailedFrame.frame;
    
    if (frame.tagClass != TagClass.UNIVERSAL) {
      throw new AsnException();
    }
    
    if (frame.tagForm != TagForm.PRIMITIVE) {
      throw new AsnException();
    }
    
    if (frame.tagNo != 10) {
      throw new AsnException();
    }
    
    return decodePart(value, frame.value);
  }
  
  public static BookCover decodePart(
      final BookCover value,
      final ByteArrayWindow window) throws AsnException {
    final long intValue = TLV.longValue(window);
    
    if (intValue == BookCover.hardCover.value) {
      return BookCover.hardCover;
    } else if (intValue == BookCover.paperBack.value) {
      return BookCover.paperBack;
    } else {
      throw new AsnException();
    }
  }

  public static BerWriter decodePart(final Books value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final Books value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final BookPrice value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final BookPrice value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final BookPrices value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final BookPrices value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final BookCover value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final BookCover value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final Book value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final Book value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final Journals value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final Journals value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final Item value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final Item value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final Journal value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final Journal value) throws AsnException {
    return decode_(value);
  }

  public static BerWriter decodePart(final Items value) throws AsnException {
    return decodePart_(value);
  }

  public static BerWriter decode(final Items value) throws AsnException {
    return decode_(value);
  }
}
