/* This file was generated by asn1gen */

package moo.model.ASNEXAMPLES;

import org.asn1gen.runtime.java.*;

import static org.asn1gen.runtime.java.Statics.*;

public abstract class Item extends org.asn1gen.runtime.java.AsnChoice {
  /*GenJava.scala:1112*/
  public Option<Book> getBook() {
    return None.instance();
  }

  public Option<Journal> getJournal() {
    return None.instance();
  }
  /*GenJava.scala:1085*/
  public Item_book withBook(final Book value) {
    return new Item_book(value);}

  public Item_journal withJournal(final Journal value) {
    return new Item_journal(value);}
}
/*GenJava.scala:260*//*GenJava.scala:1003*//*GenJava.scala:1003*/
